### ISSUE TITLE
Build failing for missing class org/apache/velocity/context/Context

### ISSUE THREAD

**Issue by dewanprakash** [temyers/cucumber-jvm-parallel-plugin#66] opened 2016-09-15 11:09 UTC
Hi,

I setup the plug-in as described @ https://github.com/temyers/cucumber-jvm-parallel-plugin. 
However, I am facing following error, when trying maven build. The issue is same with v1.2.0, 1.2.1 and 1.3.0 as well.

_Failed to execute goal com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners (generateRunners) on project colspace: Execution generateRunners of goal com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners failed: A required class was missing while executing com.github.temyers:cucumber-jvm-parallel-plugin:1.3.0:generateRunners: org/apache/velocity/context/Context_

Please help!!

**Comment by sugatmankar** [comment] 2016-09-16 07:21
Hello @dewanprakash make sure your .m2/repository has successfully installed below dependency.

<dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>1.7</version>
        </dependency>

**Comment by dewanprakash** [comment] 2016-09-16 08:20
Yes. I already had velocity dependency resolved successfully but still have the issue

**Comment by dewanprakash** [comment] 2016-09-22 19:21
I can see that the dependency is resolved perfectly fine in .m2/repository, however still seeing this issue.

**Comment by temyers** [comment] 2016-09-27 09:42
Are you using velocity in your project (is it a project dependency)?
what's the result of running `mvn dependency:tree`?
Also, what version of Java are you using?

This looks like a runtime classpath issue related to your project dependencies.

**Comment by dewanprakash** [comment] 2016-09-27 10:29
velocity is added as maven dependency
`mvn dependency:tree` results in` BUILD SUCCESS`
Java 1.7

**Comment by temyers** [comment] 2016-09-28 02:12
What's the full output of `mvn dependency:tree`?

**Comment by dewanprakash** [comment] 2016-09-28 04:52
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building xx-xxxxxxx 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/springsource-milestones/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/public/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/third-party/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-selenium-java/maven-metadata.xml (3 KB at 1.8 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/com/applitools/eyes-selenium-java/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/com/applitools/eyes-selenium-java/maven-metadata.xml (3 KB at 3.7 KB/sec)
Downloaded: http://repo.jenkins-ci.org/public/com/applitools/eyes-selenium-java/maven-metadata.xml (3 KB at 2.1 KB/sec)
Downloaded: https://repository.jboss.org/nexus/content/groups/public/com/applitools/eyes-selenium-java/maven-metadata.xml (221 B at 0.1 KB/sec)
[WARNING] Could not transfer metadata com.applitools:eyes-selenium-java/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/com/applitools/eyes-selenium-java/maven-metadata.xml. Error code 503, Service Unavailable
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.pom
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.pom (2 KB at 1.6 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-sdk-java-parent/2.54/eyes-sdk-java-parent-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-sdk-java-parent/2.54/eyes-sdk-java-parent-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-parent/2.54/eyes-sdk-java-parent-2.54.pom
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-parent/2.54/eyes-sdk-java-parent-2.54.pom (7 KB at 10.3 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.pom
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.pom (2 KB at 1.8 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.pom
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.pom (2 KB at 1.9 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.pom
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.pom
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.pom (2 KB at 2.0 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/springsource-milestones/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/third-party/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (3 KB at 4.5 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (3 KB at 5.0 KB/sec)
Downloaded: http://repo.jenkins-ci.org/public/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (3 KB at 3.8 KB/sec)
Downloaded: https://repository.jboss.org/nexus/content/groups/public/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (349 B at 0.2 KB/sec)
[WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/org/seleniumhq/selenium/selenium-java/maven-metadata.xml. Error code 503, Service Unavailable
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/io/appium/java-client/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/io/appium/java-client/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/springsource-milestones/io/appium/java-client/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/io/appium/java-client/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/public/io/appium/java-client/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/third-party/io/appium/java-client/maven-metadata.xml
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/io/appium/java-client/maven-metadata.xml (2 KB at 2.2 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/io/appium/java-client/maven-metadata.xml
[WARNING] Checksum validation failed, expected 1db483a5ce984b8439e3c6fca0d290f33b7a74eb but is ee5215e718ea89711f1d58b4f1511818c616d77b for http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/io/appium/java-client/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/io/appium/java-client/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/io/appium/java-client/maven-metadata.xml (2 KB at 2.1 KB/sec)
Downloaded: http://repo.jenkins-ci.org/public/io/appium/java-client/maven-metadata.xml (2 KB at 1.5 KB/sec)
Downloaded: https://repository.jboss.org/nexus/content/groups/public/io/appium/java-client/maven-metadata.xml (209 B at 0.1 KB/sec)
[WARNING] Could not transfer metadata io.appium:java-client/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/io/appium/java-client/maven-metadata.xml. Error code 503, Service Unavailable
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/springsource-milestones/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml (771 B at 1.5 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/third-party/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.jenkins-ci.org/public/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.uncommons:reportng:1.8.7-SNAPSHOT/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/org/uncommons/reportng/1.8.7-SNAPSHOT/maven-metadata.xml. Error code 503, Service Unavailable
Downloading: http://repo.maven.apache.org/maven2/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.jar
Downloaded: http://repo.maven.apache.org/maven2/com/applitools/eyes-selenium-java/2.54/eyes-selenium-java-2.54.jar (84 KB at 76.1 KB/sec)
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-snapshots/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/dds-releases/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.jar
Downloading: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.jar
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-connectivity-java-jersey2x/2.54/eyes-connectivity-java-jersey2x-2.54.jar (12 KB at 9.4 KB/sec)
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-common-java/2.54/eyes-common-java-2.54.jar (45 KB at 23.9 KB/sec)
Downloaded: http://nexus.rho.dds.net/nexus/content/repositories/atlassian-maven-repo/com/applitools/eyes-sdk-java-jersey2x/2.54/eyes-sdk-java-jersey2x-2.54.jar (39 KB at 19.6 KB/sec)
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ mo-lumina ---
[WARNING] Failure to transfer org.seleniumhq.selenium:selenium-java/maven-metadata.xml from https://oss.sonatype.org/content/repositories/springsource-milestones was cached in the local repository, resolution will not be reattempted until the update interval of springsource-milestones has elapsed or updates are forced. Original error: Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/org/seleniumhq/selenium/selenium-java/maven-metadata.xml. Error code 503, Service Unavailable
[WARNING] Failure to transfer io.appium:java-client/maven-metadata.xml from https://oss.sonatype.org/content/repositories/springsource-milestones was cached in the local repository, resolution will not be reattempted until the update interval of springsource-milestones has elapsed or updates are forced. Original error: Could not transfer metadata io.appium:java-client/maven-metadata.xml from/to springsource-milestones (https://oss.sonatype.org/content/repositories/springsource-milestones): Failed to transfer https://oss.sonatype.org/content/repositories/springsource-milestones/io/appium/java-client/maven-metadata.xml. Error code 503, Service Unavailable
[INFO] com.mediaocean.lumina.uiautomation:mo-lumina:jar:0.0.1-SNAPSHOT
[INFO] +- com.google.inject:guice:jar:3.0:test
[INFO] |  +- javax.inject:javax.inject:jar:1:test
[INFO] |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  \- commons-lang:commons-lang:jar:2.4:compile
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:2.44.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-htmlunit-driver:jar:2.44.0:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit:jar:2.15:compile
[INFO] |  |  |  +- xalan:xalan:jar:2.7.1:compile
[INFO] |  |  |  |  \- xalan:serializer:jar:2.7.1:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpmime:jar:4.3.3:compile
[INFO] |  |  |  +- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.15:compile
[INFO] |  |  |  +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  |  |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  |  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.21:compile
[INFO] |  |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.14:compile
[INFO] |  |  |  |  \- org.w3c.css:sac:jar:1.3:compile
[INFO] |  |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-websocket:jar:8.1.15.v20140411:compile
[INFO] |  |  |     +- org.eclipse.jetty:jetty-util:jar:8.1.15.v20140411:compile
[INFO] |  |  |     +- org.eclipse.jetty:jetty-io:jar:8.1.15.v20140411:compile
[INFO] |  |  |     \- org.eclipse.jetty:jetty-http:jar:8.1.15.v20140411:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.3.4:compile
[INFO] |  |     \- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:2.44.0:compile
[INFO] |  \- org.webbitserver:webbit:jar:0.4.14:compile
[INFO] |     \- io.netty:netty:jar:3.5.2.Final:compile
[INFO] +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.44.0:compile
[INFO] |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:2.44.0:compile
[INFO] |     +- cglib:cglib-nodep:jar:2.1_3:compile
[INFO] |     +- com.google.code.gson:gson:jar:2.3:compile
[INFO] |     \- org.seleniumhq.selenium:selenium-api:jar:2.44.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.44.0:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  \- org.apache.commons:commons-exec:jar:1.1:compile
[INFO] +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.44.0:compile
[INFO] |  +- net.java.dev.jna:jna:jar:3.4.0:compile
[INFO] |  \- net.java.dev.jna:platform:jar:3.4.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-support:jar:2.44.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-server:jar:2.44.0:test
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.48:test
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.48:test
[INFO] |  +- mx4j:mx4j-tools:jar:3.0.1:test
[INFO] |  +- org.mortbay.jetty:servlet-api-2.5:jar:6.1.9:test
[INFO] |  +- org.seleniumhq.selenium:jetty-repacked:jar:7.6.1:test
[INFO] |  +- org.seleniumhq.selenium:jetty-rc-repacked:jar:5:test
[INFO] |  +- net.jcip:jcip-annotations:jar:1.0:test
[INFO] |  \- org.yaml:snakeyaml:jar:1.8:test
[INFO] +- com.opera:operadriver:jar:1.5:test
[INFO] |  +- com.opera:operalaunchers:jar:1.1:test
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.4.1:test
[INFO] |  +- commons-jxpath:commons-jxpath:jar:1.3:test
[INFO] |  \- org.ini4j:ini4j:jar:0.5.2:test
[INFO] +- org.testng:testng:jar:6.9.10:compile
[INFO] |  +- com.beust:jcommander:jar:1.48:compile
[INFO] |  \- org.beanshell:bsh:jar:2.0b4:compile
[INFO] +- info.cukes:cucumber-jvm:pom:1.2.4:compile
[INFO] +- info.cukes:cucumber-java:jar:1.2.4:compile
[INFO] |  \- info.cukes:cucumber-core:jar:1.2.4:compile
[INFO] |     +- info.cukes:cucumber-html:jar:0.2.3:compile
[INFO] |     +- info.cukes:cucumber-jvm-deps:jar:1.0.5:compile
[INFO] |     \- info.cukes:gherkin:jar:2.12.2:compile
[INFO] +- ant:ant-apache-log4j:jar:1.6.5:compile
[INFO] +- org.json:json:jar:20131018:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] +- com.applitools:eyes-selenium-java:jar:RELEASE:compile
[INFO] |  +- com.applitools:eyes-sdk-java-jersey2x:jar:2.54:compile
[INFO] |  |  +- com.applitools:eyes-common-java:jar:2.54:compile
[INFO] |  |  |  +- org.imgscalr:imgscalr-lib:jar:4.2:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.5.1:compile
[INFO] |  |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.5.1:compile
[INFO] |  |  \- com.applitools:eyes-connectivity-java-jersey2x:jar:2.54:compile
[INFO] |  |     +- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.16:compile
[INFO] |  |     |  +- org.glassfish.jersey.core:jersey-common:jar:2.16:compile
[INFO] |  |     |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |     |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.16:compile
[INFO] |  |     |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |     |  \- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |     \- org.glassfish.jersey.core:jersey-client:jar:2.16:compile
[INFO] |  |        +- org.glassfish.hk2:hk2-api:jar:2.4.0-b09:compile
[INFO] |  |        |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b09:compile
[INFO] |  |        |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b09:compile
[INFO] |  |        +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b09:compile
[INFO] |  |        \- org.glassfish.hk2:hk2-locator:jar:2.4.0-b09:compile
[INFO] |  |           \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  \- io.appium:java-client:jar:RELEASE:compile
[INFO] |     +- commons-validator:commons-validator:jar:1.5.1:compile
[INFO] |     |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |     |  \- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |     +- org.springframework:spring-context:jar:4.3.2.RELEASE:compile
[INFO] |     |  +- org.springframework:spring-aop:jar:4.3.2.RELEASE:compile
[INFO] |     |  +- org.springframework:spring-beans:jar:4.3.2.RELEASE:compile
[INFO] |     |  +- org.springframework:spring-core:jar:4.3.2.RELEASE:compile
[INFO] |     |  \- org.springframework:spring-expression:jar:4.3.2.RELEASE:compile
[INFO] |     \- org.aspectj:aspectjweaver:jar:1.8.9:compile
[INFO] +- info.cukes:cucumber-picocontainer:jar:1.2.4:test
[INFO] |  \- org.picocontainer:picocontainer:jar:2.15:test
[INFO] +- info.cukes:cucumber-testng:jar:1.2.4:compile
[INFO] +- org.uncommons:reportng:jar:1.8.7-SNAPSHOT:test
[INFO] \- com.github.temyers:cucumber-jvm-parallel-plugin:maven-plugin:1.2.1:compile
[INFO]    \- com.google.guava:guava:jar:19.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.418s
[INFO] Finished at: Wed Sep 28 10:18:20 IST 2016
[INFO] Final Memory: 16M/210M
[INFO] ------------------------------------------------------------------------

**Comment by temyers** [comment] 2016-09-28 05:31
Ok, your project depends on Velocity which could be causing a conflict.  Otherwise, it may be your environment setup.

Please could you use the [simple-it project](https://github.com/temyers/cucumber-jvm-parallel-plugin/tree/master/src/it/junit/simple-it) to create a stripped down project that can demonstrate the problem.

Creating a sample project with velocity as a dependency to the above did not reproduce the issue for me.

I'm closing this as unreproducible at this time.

**Closed by temyers** 2016-09-28 05:31 UTC
Labels: bug, invalid
