### ISSUE TITLE
Inject code into generated runner class body?

### ISSUE THREAD

**Issue by TheKeyboardKowboy** [temyers/cucumber-jvm-parallel-plugin#70] opened 2016-10-26 18:54 UTC
I have a Cucumber/Selenium framework and have each test designed to extend a class in order to initialize the web driver upon suite execution and then subsequently destroy the web driver after suite execution.

Is there any way to get the generated runner classes to extend a class?
Any way to inject code into the body of the generated runner class, in order to add @BeforeClass and @AfterClass hooks?

I understand that my overall design may need to change in order to support parallelization with Selenium,
but was hoping there'd be a way to manipulate the generated runner class.

Thank you.

**Comment by temyers** [comment] 2016-10-27 01:00
At the moment, no, but contributions welcome! 

This is a duplicate of #61 - being able to specify your own template would support such advanced usage.

As a workaround, you may be able to follow the discussion [here](https://github.com/cucumber/cucumber-jvm/issues/515) to use Cucumber Before/After hooks.

I'm closing this issue as a duplicate

**Closed by temyers** 2016-10-27 01:00 UTC
Labels: duplicate
